package com.example.trackingapp.utils

object Constants {
    const val PERMISSION_REQUEST_CODE = 0

    const val SERVICE_ACTION_START_OR_RESUME = "SERVICE_ACTION_START_OR_RESUME"
    const val SERVICE_ACTION_PAUSE = "SERVICE_ACTION_PAUSE"
    const val SERVICE_ACTION_STOP = "SERVICE_ACTION_STOP"
    const val ACTION_GO_TO_MAIN_ACTIVITY = "ACTION_GO_TO_MAIN_ACTIVITY"

    const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "Tracking"
    const val NOTIFICATION_ID = 1
}